import Drake from "./Celebrity-NFT/Drake.png";
// import Eminem from "./Celebrity-NFT/Eminem.jpg";
import Tyler from "./Celebrity-NFT/Feliciathegoat.jpg";
import Frank from "./Celebrity-NFT/FrankOcean.png";
import IceCube from "./Celebrity-NFT/IceCube.png";
import Jcole from "./Celebrity-NFT/JCole.jpg";
import Jason from "./Celebrity-NFT/JasonDerulo.jpg";
import Juice from "./Celebrity-NFT/Juice.png";
import Kanye from "./Celebrity-NFT/Kanye.jpg";
import Kendrick from "./Celebrity-NFT/KendrickLamar.png";
import LilNas from "./Celebrity-NFT/LilNas.jpg";
import Nicki from "./Celebrity-NFT/NickiMinaj.jpg";
import Nipsey from "./Celebrity-NFT/NipseyHussle.jpg";
import PopSmoke from "./Celebrity-NFT/PopSmoke.jpg";
import PostMalone from "./Celebrity-NFT/PostMalone.jpg";
import Rema from "./Celebrity-NFT/Rema.jpg";
import Rihana from "./Celebrity-NFT/Rihanna.jpg";
import Snoop from "./Celebrity-NFT/SnoopDoggfinal.png";
import TheWeekend from "./Celebrity-NFT/TheWeeknd.jpg";
import Travis from "./Celebrity-NFT/TravisScott.png";
import Artist from "./Celebrity-NFT/avatar.png";
const items = [
  {
    id: 1,
    title: "Rema",
    artist: "Femi",
    artistImage: Artist,
    image: Rema,
    info: "Digital art of Rema from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 2,
    title: "Drake",
    artist: "Femi",
    artistImage: Artist,
    image: Drake,
    info: "Digital art of Drake from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },

  {
    id: 4,
    title: "Tyler",
    artist: "Femi",
    artistImage: Artist,
    image: Tyler,
    info: "Digital art of Tyler the creator from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 5,
    title: "Frank.O",
    artist: "Femi",
    artistImage: Artist,
    image: Frank,
    info: "Digital art of Frank Ocean from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 6,
    title: "Ice.C",
    artist: "Femi",
    artistImage: Artist,
    image: IceCube,
    info: "Digital art of Ice Cube from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 7,
    title: "Jcole",
    artist: "Femi",
    artistImage: Artist,
    image: Jcole,
    info: "Digital art of J Cole from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 8,
    title: "Jason.D",
    artist: "Femi",
    artistImage: Artist,
    image: Jason,
    info: "Digital art of Jason Derulo from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 9,
    title: "Juice.W",
    artist: "Femi",
    artistImage: Artist,
    image: Juice,
    info: "Digital art of Juice Wurld from our Celebrity collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 10,
    title: "Kanye.W",
    artist: "Femi",
    artistImage: Artist,
    image: Kanye,
    info: "Digital art of Kanye West from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 11,
    title: "Kendrick.L",
    artist: "Femi",
    artistImage: Artist,
    image: Kendrick,
    info: "Digital art of Kendrick Lamar from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 12,
    title: "Lil Nas",
    artist: "Femi",
    artistImage: Artist,
    image: LilNas,
    info: "Digital art of Lil Nas from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 13,
    title: "Nicki.M",
    artist: "Femi",
    artistImage: Artist,
    image: Nicki,
    info: "Digital art of Nicki Minaj from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 14,
    title: "Nipsey.H",
    artist: "Femi",
    artistImage: Artist,
    image: Nipsey,
    info: "Digital art of Nipsey Hussle from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },

  {
    id: 17,
    title: "Rihana",
    artist: "Femi",
    artistImage: Artist,
    image: Rihana,
    info: "Digital art of Rihana from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 18,
    title: "Snoop.D",
    artist: "Femi",
    artistImage: Artist,
    image: Snoop,
    info: "Digital art of Snoop Doog from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 19,
    title: "Weekend",
    artist: "Femi",
    artistImage: Artist,
    image: TheWeekend,
    info: "Digital art of The Weekend from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
  {
    id: 20,
    title: "Travis.S",
    artist: "Femi",
    artistImage: Artist,
    image: Travis,
    info: "Digital art of Travis Scott from our Celebrity collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "Celebrity Collection",
  },
];
export default items;
