import Apple from "./Polygonart-NFT/Apple.jpg";
import Avocado from "./Polygonart-NFT/Avocado.png";
import Labador from "./Polygonart-NFT/Black Labrador.png";
import BrunoMars from "./Polygonart-NFT/Bruno Mars.jpg";
import BullDog from "./Polygonart-NFT/Bulldog.jpg";
import ChrisEvans from "./Polygonart-NFT/Chris Evans.png";
import ChrisHemsWorth from "./Polygonart-NFT/Chris Hemsworth.jpg";
import CrushedCan from "./Polygonart-NFT/Crushed Can.jpg";
import Deer from "./Polygonart-NFT/Deer.png";
import DigitalBust from "./Polygonart-NFT/Digital Bust.jpg";
import Distortion from "./Polygonart-NFT/Distorttion.png";
import Elephant from "./Polygonart-NFT/Elephant.png";
import Flamingo from "./Polygonart-NFT/Flamingo.png";
import GermanShepperd from "./Polygonart-NFT/German.jpg";
import Gobiya from "./Polygonart-NFT/Gobiya.png";
import GoldenEagle from "./Polygonart-NFT/Golden Eagle.jpg";
import GOT from "./Polygonart-NFT/GOT.jpg";
import HarryPorter from "./Polygonart-NFT/Harry Potter.png";
import Holy from "./Polygonart-NFT/Holyjpg.jpg";
import HumanArt from "./Polygonart-NFT/Human Art.jpg";
import HumanGrid from "./Polygonart-NFT/Human Grid.jpg";
import HumanPolygon from "./Polygonart-NFT/HumanPolygon.jpg";
import KiraConley from "./Polygonart-NFT/Kira Conley.png";
import Heart from "./Polygonart-NFT/Love.jpg";
import MarkRuffalo from "./Polygonart-NFT/Mark Ruffalo.jpg";
import MetalLion from "./Polygonart-NFT/Metal Lion.jpg";
import Portrait from "./Polygonart-NFT/Portrait Zone.jpg";
import HumanPortrait from "./Polygonart-NFT/Portrait.jpg";
import Princess from "./Polygonart-NFT/Princess.jpg";
import Prism from "./Polygonart-NFT/Prism.jpg";
import Rabbit from "./Polygonart-NFT/Rabbit.jpg";
import Rdj from "./Polygonart-NFT/Robert Downey Jr.jpg";
import Samuel from "./Polygonart-NFT/Samuel.png";
import Scarett from "./Polygonart-NFT/Scarlett Johansson.png";
import Skull from "./Polygonart-NFT/Skull.jpg";
import StanLee from "./Polygonart-NFT/Stan Lee.jpg";
import ThessaThompson from "./Polygonart-NFT/Tessa Thompson.jpg";
import Universo from "./Polygonart-NFT/Universo.png";
import Waterfall from "./Polygonart-NFT/Waterfall.jpg";
import Wizard from "./Polygonart-NFT/Wizard.jpg";
