import Avocado from "./Polygonart-NFT/Avocado.png";
import Labador from "./Polygonart-NFT/BlackLabrador.png";
import CrushedCan from "./Polygonart-NFT/CrushedCan.jpg";
import Deer from "./Polygonart-NFT/Deer.png";
import DigitalBust from "./Polygonart-NFT/DigitaBust.jpg";
import Distortion from "./Polygonart-NFT/Distorttion.png";
import Elephant from "./Polygonart-NFT/Elephant.png";
import GermanShepperd from "./Polygonart-NFT/German.jpg";
import GoldenEagle from "./Polygonart-NFT/GoldenEagle.jpg";
import Holy from "./Polygonart-NFT/Holyjpg.jpg";
import HumanArt from "./Polygonart-NFT/HumanArt.jpg";
import HumanGrid from "./Polygonart-NFT/HumanGrid.jpg";
import Heart from "./Polygonart-NFT/Love.jpg";
import Portrait from "./Polygonart-NFT/PortraitZone.jpg";
import HumanPortrait from "./Polygonart-NFT/Portrait.jpg";
import Rabbit from "./Polygonart-NFT/Rabbit.jpg";
import Skull from "./Polygonart-NFT/Skull.jpg";
import Waterfall from "./Polygonart-NFT/Waterfall.jpg";
import Wizard from "./Polygonart-NFT/Wizard.jpg";
import Artist from "./Polygonart-NFT/avatar.png";
const items = [
  {
    id: 1,
    title: "Avocado",
    artist: "Femi",
    artistImage: Artist,
    image: Avocado,
    info: "Digital art of Avocado from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 2,
    title: "Labador",
    artist: "Femi",
    artistImage: Artist,
    image: Labador,
    info: "Digital art of a Labador from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },

  {
    id: 3,
    title: "Crushed Can",
    artist: "Femi",
    artistImage: Artist,
    image: CrushedCan,
    info: "Digital art of a Crushed Can from our PolygonArt collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 4,
    title: "Deer",
    artist: "Femi",
    artistImage: Artist,
    image: Deer,
    info: "Digital art of a Deer from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 5,
    title: "Digital Bust",
    artist: "Femi",
    artistImage: Artist,
    image: DigitalBust,
    info: "Digital art of Digital Bust from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 6,
    title: "Distortion",
    artist: "Femi",
    artistImage: Artist,
    image: Distortion,
    info: "Digital art of Distortion Prism from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 7,
    title: "Elephant",
    artist: "Femi",
    artistImage: Artist,
    image: Elephant,
    info: "Digital art of a Elephant from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },

  {
    id: 8,
    title: "German.S",
    artist: "Femi",
    artistImage: Artist,
    image: GermanShepperd,
    info: "Digital art of a German Sheppard from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },

  {
    id: 9,
    title: "GoldenEagle",
    artist: "Femi",
    artistImage: Artist,
    image: GoldenEagle,
    info: "Digital art of a Golden Eagle from our PolygonArt collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },

  {
    id: 10,
    title: "Holy",
    artist: "Femi",
    artistImage: Artist,
    image: Holy,
    info: "Digital art of Holy from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 11,
    title: "Human Art",
    artist: "Femi",
    artistImage: Artist,
    image: HumanArt,
    info: "Digital art of Human Art from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 12,
    title: "Human Grid",
    artist: "Femi",
    artistImage: Artist,
    image: HumanGrid,
    info: "Digital art of a Human Grid from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 13,
    title: "Heart",
    artist: "Femi",
    artistImage: Artist,
    image: Heart,
    info: "Digital art of Heart from our PolygonArt collection",
    cover: true,
    center: true,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },

  {
    id: 14,
    title: "Portrait",
    artist: "Femi",
    artistImage: Artist,
    image: Portrait,
    info: "Digital art of a Portrait from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 15,
    title: "Human Portrait",
    artist: "Femi",
    artistImage: Artist,
    image: HumanPortrait,
    info: "Digital art of a Human Portrait from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 16,
    title: "Rabbit",
    artist: "Femi",
    artistImage: Artist,
    image: Rabbit,
    info: "Digital art of a Rabbit from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },

  {
    id: 17,
    title: "Skull",
    artist: "Femi",
    artistImage: Artist,
    image: Skull,
    info: "Digital art of a Skull from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },

  {
    id: 18,
    title: "Waterfall",
    artist: "Femi",
    artistImage: Artist,
    image: Waterfall,
    info: "Digital art of a Waterfall from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
  {
    id: 19,
    title: "Wizard",
    artist: "Femi",
    artistImage: Artist,
    image: Wizard,
    info: "Digital art of a Wizard from our PolygonArt collection",
    cover: true,
    center: false,
    price: "0.2ETH",
    collection: "PolygonArt Collection",
  },
];
export default items;
